version: '2'

services:
  tunnel:
    container_name: plex-server
    image: packetriot/pktriot:latest
    restart: unless-stopped
    volumes:
      - <preferred-dir>\pktriot:/data
      - <preferred-dir>\www:/www:ro

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Stockholm
      - PLEX_CLAIM=<get this from, plex.tv/claim>
    hostname: mediaserver
    volumes:
      - <preferred-dir>\plex\config:/config
      - <preferred-dir>\plex\transcode:/transcode
      - <preferred-dir>\movies:/movies
      - <preferred-dir>\myvideos:/myvideos
      - <preferred-dir>\photos:/photos
      - <preferred-dir>\music:/music